[logger]
level = "INFO"

[httpserver]
host = "100.90.10.10"
port = 5001

[storage]
driver = "sql"

[database]
host = "100.90.10.9"
port = 5432
dbname = "calendar_testing"
username = "user"
password = "user"

[rabbit]
host = "100.90.10.3"
port = 5672
name = "calendar_testing"
user = "user"
password = "user"
