[logger]
level = "INFO"

[httpserver]
host = "127.0.0.1"
port = 5000

[storage]
driver = "in-memory"

[database]
host = "127.0.0.1"
port = 5432
dbname = "calendar"
username = "user"
password = "pass"

[rabbit]
name = "calendar"
user = "guest"
password = "quest"
host = "127.0.0.1"
port = 5672
