[logger]
level = "INFO"

[httpserver]
host = "127.0.0.1"
port = 5000

[storage]
driver = "in-memory"

[database]
host = "10.90.0.5"
port = 5432
dbname = "calendar_testing"
username = "user"
password = "user"

[rabbit]
name = "calendar"
user = "user"
password = "user"
host = "10.90.0.8"
port = 5672