[logger]
level = "INFO"

[httpserver]
host = "100.90.10.4"
port = 5000

[storage]
driver = "sql"

[database]
host = "100.90.10.2"
port = 5432
dbname = "calendar"
username = "user"
password = "user"

[rabbit]
host = "100.90.10.3"
port = 5672
name = "calendar"
user = "user"
password = "user"
