apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: calendar
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi