apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: calendar
  name: calendar-deployment
  labels:
    app: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: anrilee/calendar_app:latest
          ports:
            - containerPort: 5005

---
apiVersion: v1
kind: Service
metadata:
  namespace: calendar
  name: calendar-service
spec:
  selector:
    app: calendar
  ports:
    - name: calendar
      port: 5005
      targetPort: 5005
      nodePort: 30007
  type: NodePort
